# Generated by Django 5.0.10 on 2025-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0020_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
