name: 1 - Hello World GitHub Actions 

on: # workflow trigger 
  workflow_dispatch: 
  # schedule:
  #   - cron: '30 15 * * *' # every day at 3:30 PM UTC
  # push: # git push
  #   branches:
  #     - main 

jobs: # jobs to run
  hello:
    runs-on: ubuntu-latest # runner to run the job
    steps:
      - name: Hello World
        run: echo "Hello World" # command to run