name: 1 - Hello World GitHub Actions 

on: # workflow trigger 
  workflow_dispatch: 
  push: # git push
    branches:
      - main 

jobs: # jobs to run
  hello:
    runs-on: ubuntu-latest # runner to run the job
    steps:
      - name: Hello World
        run: echo "Hello World" # command to run