name: 3 - Test Django Env Vars

on: 
  workflow_dispatch: 
  #push: 
  #  branch:
  #    - main 

jobs: 
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade 
          python -m pip install -r requirements.txt
      - name: Django Tests
        working-directory: ./src
        env:
          DJANGO_SECRET_KEY: not-good
        run: |
          python manage.py test