name: 4 - Test Django Database URL
# updated 
on: 
  workflow_dispatch: 
  #push: 
  #  branch:
  #    - main 

jobs: 
  test:
    runs-on: ubuntu-latest
    env: # setting the secret key or you can generte one on the fly like below
          DJANGO_DEBUG: 0
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
          # DJANGO_SECRET_KEY: not-good 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Setup Django Secret Key  # generating the secret key on the fly
        run: |
          MY_GEN_KEY=$(openssl rand -base64 32)
          echo "DJANGO_SECRET_KEY=$MY_GEN_KEY" >> $GITHUB_ENV
      - name: Show DATABASE_URL
        run: |
          echo ${{ env.DATABASE_URL }}
          echo $DATABASE_URL
      - name: Install Requirements
        run: |
          python -m pip install pip --upgrade 
          python -m pip install -r requirements.txt
      - name: Django Tests
        working-directory: ./src
        run: |
          python manage.py test
